name: Build and Deploy Docker image to DockerHub

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fardinhakimi:main
      
    - name: Push the Docker image to DockerHub
      run: docker push fardinhakimi:main
    
