name: Build and Deploy Docker image to DockerHub

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Source
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fardin:main


    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      
    - name: Push the Docker image to Docker Hub
      run: docker push fardinhakimi/fardin:main
    
